homepage: "https://opencv.org/"
language: c++
primary_contact: "garybradski@gmail.com"

auto_ccs:
  - "alexander.a.alekhin@gmail.com"
  - "garybradski@gmail.com"
  - "vrabaud@google.com"
  - "kusano@google.com"
  - "maksim.shabunin@gmail.com"
  - "vadim.pisarevsky@gmail.com"
  - "smorkalov.a.m@gmail.com"
  - "shiqi.yu@gmail.com"

sanitizers:
  - address
  - undefined
  - memory:
      experimental: True

labels:
  imdecode_fuzzer:
    - sundew
  imread_fuzzer:
    - sundew

main_repo: 'https://github.com/vrabaud/opencv.git'
